/*--------------------------------------------------------------------------------------
 *  Copyright 2025 Glass Devtools, Inc. All rights reserved.
 *  Licensed under the Apache License, Version 2.0. See LICENSE.txt for more information.
 *--------------------------------------------------------------------------------------*/

/** @type {import('tailwindcss').Config} */
module.exports = {
	darkMode: 'selector', // '{prefix-}dark' className is used to identify `dark:`
	content: ['./src2/**/*.{jsx,tsx}'], // uses these files to decide how to transform the css file
	theme: {
		extend: {
			typography: theme => ({
				DEFAULT: {
					css: {
						'--tw-prose-body': 'var(--pinnacleai-fg-1)',
						'--tw-prose-headings': 'var(--pinnacleai-fg-1)',
						'--tw-prose-lead': 'var(--pinnacleai-fg-2)',
						'--tw-prose-links': 'var(--pinnacleai-link-color)',
						'--tw-prose-bold': 'var(--pinnacleai-fg-1)',
						'--tw-prose-counters': 'var(--pinnacleai-fg-3)',
						'--tw-prose-bullets': 'var(--pinnacleai-fg-3)',
						'--tw-prose-hr': 'var(--pinnacleai-border-4)',
						'--tw-prose-quotes': 'var(--pinnacleai-fg-1)',
						'--tw-prose-quote-borders': 'var(--pinnacleai-border-2)',
						'--tw-prose-captions': 'var(--pinnacleai-fg-3)',
						'--tw-prose-code': 'var(--pinnacleai-fg-0)',
						'--tw-prose-pre-code': 'var(--pinnacleai-fg-0)',
						'--tw-prose-pre-bg': 'var(--pinnacleai-bg-1)',
						'--tw-prose-th-borders': 'var(--pinnacleai-border-4)',
						'--tw-prose-td-borders': 'var(--pinnacleai-border-4)',
					},
				},
			}),
			fontSize: {
				xs: '10px',
				sm: '11px',
				root: '13px',
				lg: '14px',
				xl: '16px',
				'2xl': '18px',
				'3xl': '20px',
				'4xl': '24px',
				'5xl': '30px',
				'6xl': '36px',
				'7xl': '48px',
				'8xl': '64px',
				'9xl': '72px',
			},
			// common colors to use, ordered light to dark

			colors: {
				'pinnacleai-bg-1': 'var(--pinnacleai-bg-1)',
				'pinnacleai-bg-1-alt': 'var(--pinnacleai-bg-1-alt)',
				'pinnacleai-bg-2': 'var(--pinnacleai-bg-2)',
				'pinnacleai-bg-2-alt': 'var(--pinnacleai-bg-2-alt)',
				'pinnacleai-bg-2-hover': 'var(--pinnacleai-bg-2-hover)',
				'pinnacleai-bg-3': 'var(--pinnacleai-bg-3)',


				'pinnacleai-fg-0': 'var(--pinnacleai-fg-0)',
				'pinnacleai-fg-1': 'var(--pinnacleai-fg-1)',
				'pinnacleai-fg-2': 'var(--pinnacleai-fg-2)',
				'pinnacleai-fg-3': 'var(--pinnacleai-fg-3)',
				// 'pinnacleai-fg-4': 'var(--vscode-tab-inactiveForeground)',
				'pinnacleai-fg-4': 'var(--pinnacleai-fg-4)',

				'pinnacleai-warning': 'var(--pinnacleai-warning)',

				'pinnacleai-border-1': 'var(--pinnacleai-border-1)',
				'pinnacleai-border-2': 'var(--pinnacleai-border-2)',
				'pinnacleai-border-3': 'var(--pinnacleai-border-3)',
				'pinnacleai-border-4': 'var(--pinnacleai-border-4)',

				'pinnacleai-ring-color': 'var(--pinnacleai-ring-color)',
				'pinnacleai-link-color': 'var(--pinnacleai-link-color)',

				vscode: {
					// see: https://code.visualstudio.com/api/extension-guides/webview#theming-webview-content

					// base colors
					'foreground': 'var(--vscode-foreground)',
					'disabledForeground': 'var(--vscode-disabledForeground)',
					'errorForeground': 'var(--vscode-errorForeground)',
					'descriptionForeground': 'var(--vscode-descriptionForeground)',
					'icon-foreground': 'var(--vscode-icon-foreground)',

					// button colors
					'button-background': 'var(--vscode-button-background)',
					'button-foreground': 'var(--vscode-button-foreground)',
					'button-hoverBackground': 'var(--vscode-button-hoverBackground)',
					'button-secondaryBackground': 'var(--vscode-button-secondaryBackground)',
					'button-secondaryForeground': 'var(--vscode-button-secondaryForeground)',
					'button-secondaryHoverBackground': 'var(--vscode-button-secondaryHoverBackground)',

					// dropdown colors
					'dropdown-background': 'var(--vscode-dropdown-background)',
					'dropdown-foreground': 'var(--vscode-dropdown-foreground)',
					'dropdown-border': 'var(--vscode-dropdown-border)',

					// input colors
					'input-background': 'var(--vscode-input-background)',
					'input-foreground': 'var(--vscode-input-foreground)',
					'input-border': 'var(--vscode-input-border)',
					'input-placeholderForeground': 'var(--vscode-input-placeholderForeground)',
					'inputOption-activeBorder': 'var(--vscode-inputOption-activeBorder)',
					'inputOption-hoverBackground': 'var(--vscode-inputOption-hoverBackground)',
					'inputValidation-errorBackground': 'var(--vscode-inputValidation-errorBackground)',
					'inputValidation-errorForeground': 'var(--vscode-inputValidation-errorForeground)',
					'inputValidation-errorBorder': 'var(--vscode-inputValidation-errorBorder)',
					'inputValidation-infoBackground': 'var(--vscode-inputValidation-infoBackground)',
					'inputValidation-infoForeground': 'var(--vscode-inputValidation-infoForeground)',
					'inputValidation-infoBorder': 'var(--vscode-inputValidation-infoBorder)',
					'inputValidation-warningBackground': 'var(--vscode-inputValidation-warningBackground)',
					'inputValidation-warningForeground': 'var(--vscode-inputValidation-warningForeground)',
					'inputValidation-warningBorder': 'var(--vscode-inputValidation-warningBorder)',

					// scrollbar colors
					'scrollbar-shadow': 'var(--vscode-scrollbar-shadow)',
					'scrollbarSlider-activeBackground': 'var(--vscode-scrollbarSlider-activeBackground)',
					'scrollbarSlider-background': 'var(--vscode-scrollbarSlider-background)',
					'scrollbarSlider-hoverBackground': 'var(--vscode-scrollbarSlider-hoverBackground)',

					// badge colors
					'badge-background': 'var(--vscode-badge-background)',
					'badge-foreground': 'var(--vscode-badge-foreground)',

					// progress bar colors
					'progressBar-background': 'var(--vscode-progressBar-background)',

					// list colors
					'list-activeSelectionBackground': 'var(--vscode-list-activeSelectionBackground)',
					'list-activeSelectionForeground': 'var(--vscode-list-activeSelectionForeground)',
					'list-dropBackground': 'var(--vscode-list-dropBackground)',
					'list-focusBackground': 'var(--vscode-list-focusBackground)',
					'list-focusForeground': 'var(--vscode-list-focusForeground)',
					'list-highlightForeground': 'var(--vscode-list-highlightForeground)',
					'list-hoverBackground': 'var(--vscode-list-hoverBackground)',
					'list-hoverForeground': 'var(--vscode-list-hoverForeground)',
					'list-inactiveSelectionBackground': 'var(--vscode-list-inactiveSelectionBackground)',
					'list-inactiveSelectionForeground': 'var(--vscode-list-inactiveSelectionForeground)',
					'list-inactiveFocusBackground': 'var(--vscode-list-inactiveFocusBackground)',
					'list-invalidItemForeground': 'var(--vscode-list-invalidItemForeground)',
					'list-errorForeground': 'var(--vscode-list-errorForeground)',
					'list-warningForeground': 'var(--vscode-list-warningForeground)',

					// activity bar colors
					'activityBar-background': 'var(--vscode-activityBar-background)',
					'activityBar-foreground': 'var(--vscode-activityBar-foreground)',
					'activityBar-inactiveForeground': 'var(--vscode-activityBar-inactiveForeground)',
					'activityBar-border': 'var(--vscode-activityBar-border)',
					'activityBarBadge-background': 'var(--vscode-activityBarBadge-background)',
					'activityBarBadge-foreground': 'var(--vscode-activityBarBadge-foreground)',

					// sidebar colors
					'sideBar-background': 'var(--vscode-sideBar-background)',
					'sideBar-foreground': 'var(--vscode-sideBar-foreground)',
					'sideBar-border': 'var(--vscode-sideBar-border)',
					'sideBarTitle-foreground': 'var(--vscode-sideBarTitle-foreground)',
					'sideBarSectionHeader-background': 'var(--vscode-sideBarSectionHeader-background)',
					'sideBarSectionHeader-foreground': 'var(--vscode-sideBarSectionHeader-foreground)',
					'sideBarSectionHeader-border': 'var(--vscode-sideBarSectionHeader-border)',

					// editor colors
					'editor-background': 'var(--vscode-editor-background)',
					'editor-foreground': 'var(--vscode-editor-foreground)',
					'editorLineNumber-foreground': 'var(--vscode-editorLineNumber-foreground)',
					'editorLineNumber-activeForeground': 'var(--vscode-editorLineNumber-activeForeground)',
					'editorCursor-background': 'var(--vscode-editorCursor-background)',
					'editorCursor-foreground': 'var(--vscode-editorCursor-foreground)',

					// editor selection colors
					'editor-selectionBackground': 'var(--vscode-editor-selectionBackground)',
					'editor-selectionForeground': 'var(--vscode-editor-selectionForeground)',
					'editor-inactiveSelectionBackground': 'var(--vscode-editor-inactiveSelectionBackground)',
					'editor-selectionHighlightBackground': 'var(--vscode-editor-selectionHighlightBackground)',
					'editor-selectionHighlightBorder': 'var(--vscode-editor-selectionHighlightBorder)',

					// editor find colors
					'editor-findMatchBackground': 'var(--vscode-editor-findMatchBackground)',
					'editor-findMatchHighlightBackground': 'var(--vscode-editor-findMatchHighlightBackground)',
					'editor-findRangeHighlightBackground': 'var(--vscode-editor-findRangeHighlightBackground)',
					'editor-findMatchBorder': 'var(--vscode-editor-findMatchBorder)',
					'editor-findMatchHighlightBorder': 'var(--vscode-editor-findMatchHighlightBorder)',
					'editor-findRangeHighlightBorder': 'var(--vscode-editor-findRangeHighlightBorder)',

					// editor hover colors
					'editor-hoverHighlightBackground': 'var(--vscode-editor-hoverHighlightBackground)',
					'editor-linkActiveForeground': 'var(--vscode-editor-linkActiveForeground)',

					// editor widget colors
					'editorWidget-background': 'var(--vscode-editorWidget-background)',
					'editorWidget-foreground': 'var(--vscode-editorWidget-foreground)',
					'editorWidget-border': 'var(--vscode-editorWidget-border)',
					'editorWidget-resizeBorder': 'var(--vscode-editorWidget-resizeBorder)',

					// editor suggest colors
					'editorSuggestWidget-background': 'var(--vscode-editorSuggestWidget-background)',
					'editorSuggestWidget-border': 'var(--vscode-editorSuggestWidget-border)',
					'editorSuggestWidget-foreground': 'var(--vscode-editorSuggestWidget-foreground)',
					'editorSuggestWidget-highlightForeground': 'var(--vscode-editorSuggestWidget-highlightForeground)',
					'editorSuggestWidget-selectedBackground': 'var(--vscode-editorSuggestWidget-selectedBackground)',
					'editorSuggestWidget-selectedForeground': 'var(--vscode-editorSuggestWidget-selectedForeground)',

					// editor hover widget colors
					'editorHoverWidget-background': 'var(--vscode-editorHoverWidget-background)',
					'editorHoverWidget-foreground': 'var(--vscode-editorHoverWidget-foreground)',
					'editorHoverWidget-border': 'var(--vscode-editorHoverWidget-border)',

					// peek view colors
					'peekView-border': 'var(--vscode-peekView-border)',
					'peekViewEditor-background': 'var(--vscode-peekViewEditor-background)',
					'peekViewEditorGutter-background': 'var(--vscode-peekViewEditorGutter-background)',
					'peekViewEditor-matchHighlightBackground': 'var(--vscode-peekViewEditor-matchHighlightBackground)',
					'peekViewEditor-matchHighlightBorder': 'var(--vscode-peekViewEditor-matchHighlightBorder)',
					'peekViewResult-background': 'var(--vscode-peekViewResult-background)',
					'peekViewResult-fileForeground': 'var(--vscode-peekViewResult-fileForeground)',
					'peekViewResult-lineForeground': 'var(--vscode-peekViewResult-lineForeground)',
					'peekViewResult-matchHighlightBackground': 'var(--vscode-peekViewResult-matchHighlightBackground)',
					'peekViewResult-selectionBackground': 'var(--vscode-peekViewResult-selectionBackground)',
					'peekViewResult-selectionForeground': 'var(--vscode-peekViewResult-selectionForeground)',
					'peekViewTitle-background': 'var(--vscode-peekViewTitle-background)',
					'peekViewTitleDescription-foreground': 'var(--vscode-peekViewTitleDescription-foreground)',
					'peekViewTitleLabel-foreground': 'var(--vscode-peekViewTitleLabel-foreground)',

					// merge colors
					'merge-currentHeaderBackground': 'var(--vscode-merge-currentHeaderBackground)',
					'merge-currentContentBackground': 'var(--vscode-merge-currentContentBackground)',
					'merge-incomingHeaderBackground': 'var(--vscode-merge-incomingHeaderBackground)',
					'merge-incomingContentBackground': 'var(--vscode-merge-incomingContentBackground)',
					'merge-border': 'var(--vscode-merge-border)',
					'merge-commonContentBackground': 'var(--vscode-merge-commonContentBackground)',
					'merge-commonHeaderBackground': 'var(--vscode-merge-commonHeaderBackground)',
					'editorOverviewRuler-currentContentForeground': 'var(--vscode-editorOverviewRuler-currentContentForeground)',
					'editorOverviewRuler-incomingContentForeground': 'var(--vscode-editorOverviewRuler-incomingContentForeground)',
					'editorOverviewRuler-commonContentForeground': 'var(--vscode-editorOverviewRuler-commonContentForeground)',

					// panel colors
					'panel-background': 'var(--vscode-panel-background)',
					'panel-border': 'var(--vscode-panel-border)',
					'panel-dropBorder': 'var(--vscode-panel-dropBorder)',
					'panelTitle-activeBorder': 'var(--vscode-panelTitle-activeBorder)',
					'panelTitle-activeForeground': 'var(--vscode-panelTitle-activeForeground)',
					'panelTitle-inactiveForeground': 'var(--vscode-panelTitle-inactiveForeground)',
					'panelInput-border': 'var(--vscode-panelInput-border)',

					// status bar colors
					'statusBar-background': 'var(--vscode-statusBar-background)',
					'statusBar-foreground': 'var(--vscode-statusBar-foreground)',
					'statusBar-border': 'var(--vscode-statusBar-border)',
					'statusBar-debuggingBackground': 'var(--vscode-statusBar-debuggingBackground)',
					'statusBar-debuggingForeground': 'var(--vscode-statusBar-debuggingForeground)',
					'statusBar-debuggingBorder': 'var(--vscode-statusBar-debuggingBorder)',
					'statusBar-noFolderForeground': 'var(--vscode-statusBar-noFolderForeground)',
					'statusBar-noFolderBackground': 'var(--vscode-statusBar-noFolderBackground)',
					'statusBar-noFolderBorder': 'var(--vscode-statusBar-noFolderBorder)',
					'statusBarItem-activeBackground': 'var(--vscode-statusBarItem-activeBackground)',
					'statusBarItem-hoverBackground': 'var(--vscode-statusBarItem-hoverBackground)',
					'statusBarItem-prominentForeground': 'var(--vscode-statusBarItem-prominentForeground)',
					'statusBarItem-prominentBackground': 'var(--vscode-statusBarItem-prominentBackground)',
					'statusBarItem-prominentHoverBackground': 'var(--vscode-statusBarItem-prominentHoverBackground)',
					'statusBarItem-remoteBackground': 'var(--vscode-statusBarItem-remoteBackground)',
					'statusBarItem-remoteForeground': 'var(--vscode-statusBarItem-remoteForeground)',
					'statusBarItem-errorBackground': 'var(--vscode-statusBarItem-errorBackground)',
					'statusBarItem-errorForeground': 'var(--vscode-statusBarItem-errorForeground)',
					'statusBarItem-warningBackground': 'var(--vscode-statusBarItem-warningBackground)',
					'statusBarItem-warningForeground': 'var(--vscode-statusBarItem-warningForeground)',

					// title bar colors
					'titleBar-activeBackground': 'var(--vscode-titleBar-activeBackground)',
					'titleBar-activeForeground': 'var(--vscode-titleBar-activeForeground)',
					'titleBar-inactiveBackground': 'var(--vscode-titleBar-inactiveBackground)',
					'titleBar-inactiveForeground': 'var(--vscode-titleBar-inactiveForeground)',
					'titleBar-border': 'var(--vscode-titleBar-border)',

					// menu bar colors
					'menubar-selectionForeground': 'var(--vscode-menubar-selectionForeground)',
					'menubar-selectionBackground': 'var(--vscode-menubar-selectionBackground)',
					'menubar-selectionBorder': 'var(--vscode-menubar-selectionBorder)',
					'menu-foreground': 'var(--vscode-menu-foreground)',
					'menu-background': 'var(--vscode-menu-background)',
					'menu-selectionForeground': 'var(--vscode-menu-selectionForeground)',
					'menu-selectionBackground': 'var(--vscode-menu-selectionBackground)',
					'menu-selectionBorder': 'var(--vscode-menu-selectionBorder)',
					'menu-separatorBackground': 'var(--vscode-menu-separatorBackground)',
					'menu-border': 'var(--vscode-menu-border)',

					// notification colors
					'notificationCenter-border': 'var(--vscode-notificationCenter-border)',
					'notificationCenterHeader-foreground': 'var(--vscode-notificationCenterHeader-foreground)',
					'notificationCenterHeader-background': 'var(--vscode-notificationCenterHeader-background)',
					'notificationToast-border': 'var(--vscode-notificationToast-border)',
					'notifications-foreground': 'var(--vscode-notifications-foreground)',
					'notifications-background': 'var(--vscode-notifications-background)',
					'notifications-border': 'var(--vscode-notifications-border)',
					'notificationLink-foreground': 'var(--vscode-notificationLink-foreground)',
					'notificationsErrorIcon-foreground': 'var(--vscode-notificationsErrorIcon-foreground)',
					'notificationsWarningIcon-foreground': 'var(--vscode-notificationsWarningIcon-foreground)',
					'notificationsInfoIcon-foreground': 'var(--vscode-notificationsInfoIcon-foreground)',

					// extension colors
					'extensionButton-prominentForeground': 'var(--vscode-extensionButton-prominentForeground)',
					'extensionButton-prominentBackground': 'var(--vscode-extensionButton-prominentBackground)',
					'extensionButton-prominentHoverBackground': 'var(--vscode-extensionButton-prominentHoverBackground)',
					'extensionBadge-remoteBackground': 'var(--vscode-extensionBadge-remoteBackground)',
					'extensionBadge-remoteForeground': 'var(--vscode-extensionBadge-remoteForeground)',
					'extensionIcon-starForeground': 'var(--vscode-extensionIcon-starForeground)',
					'extensionIcon-verifiedForeground': 'var(--vscode-extensionIcon-verifiedForeground)',
					'extensionIcon-preReleaseForeground': 'var(--vscode-extensionIcon-preReleaseForeground)',
					'extensionIcon-sponsorForeground': 'var(--vscode-extensionIcon-sponsorForeground)',

					// quick picker colors
					'pickerGroup-border': 'var(--vscode-pickerGroup-border)',
					'pickerGroup-foreground': 'var(--vscode-pickerGroup-foreground)',
					'quickInput-background': 'var(--vscode-quickInput-background)',
					'quickInput-foreground': 'var(--vscode-quickInput-foreground)',
					'quickInputList-focusBackground': 'var(--vscode-quickInputList-focusBackground)',
					'quickInputList-focusForeground': 'var(--vscode-quickInputList-focusForeground)',
					'quickInputList-focusIconForeground': 'var(--vscode-quickInputList-focusIconForeground)',

					// keybinding label colors
					'keybindingLabel-background': 'var(--vscode-keybindingLabel-background)',
					'keybindingLabel-foreground': 'var(--vscode-keybindingLabel-foreground)',
					'keybindingLabel-border': 'var(--vscode-keybindingLabel-border)',
					'keybindingLabel-bottomBorder': 'var(--vscode-keybindingLabel-bottomBorder)',

					// keyboard shortcut table colors
					'keybindingTable-headerBackground': 'var(--vscode-keybindingTable-headerBackground)',
					'keybindingTable-rowsBackground': 'var(--vscode-keybindingTable-rowsBackground)',

					// integrated terminal colors
					'terminal-background': 'var(--vscode-terminal-background)',
					'terminal-border': 'var(--vscode-terminal-border)',
					'terminal-foreground': 'var(--vscode-terminal-foreground)',
					'terminal-ansiBlack': 'var(--vscode-terminal-ansiBlack)',
					'terminal-ansiBlue': 'var(--vscode-terminal-ansiBlue)',
					'terminal-ansiBrightBlack': 'var(--vscode-terminal-ansiBrightBlack)',
					'terminal-ansiBrightBlue': 'var(--vscode-terminal-ansiBrightBlue)',
					'terminal-ansiBrightCyan': 'var(--vscode-terminal-ansiBrightCyan)',
					'terminal-ansiBrightGreen': 'var(--vscode-terminal-ansiBrightGreen)',
					'terminal-ansiBrightMagenta': 'var(--vscode-terminal-ansiBrightMagenta)',
					'terminal-ansiBrightRed': 'var(--vscode-terminal-ansiBrightRed)',
					'terminal-ansiBrightWhite': 'var(--vscode-terminal-ansiBrightWhite)',
					'terminal-ansiBrightYellow': 'var(--vscode-terminal-ansiBrightYellow)',
					'terminal-ansiCyan': 'var(--vscode-terminal-ansiCyan)',
					'terminal-ansiGreen': 'var(--vscode-terminal-ansiGreen)',
					'terminal-ansiMagenta': 'var(--vscode-terminal-ansiMagenta)',
					'terminal-ansiRed': 'var(--vscode-terminal-ansiRed)',
					'terminal-ansiWhite': 'var(--vscode-terminal-ansiWhite)',
					'terminal-ansiYellow': 'var(--vscode-terminal-ansiYellow)',
					'terminal-selectionBackground': 'var(--vscode-terminal-selectionBackground)',
					'terminal-inactiveSelectionBackground': 'var(--vscode-terminal-inactiveSelectionBackground)',
					'terminal-findMatchBackground': 'var(--vscode-terminal-findMatchBackground)',
					'terminal-findMatchBorder': 'var(--vscode-terminal-findMatchBorder)',
					'terminal-findMatchHighlightBackground': 'var(--vscode-terminal-findMatchHighlightBackground)',
					'terminal-findMatchHighlightBorder': 'var(--vscode-terminal-findMatchHighlightBorder)',
					'terminal-hoverHighlightBackground': 'var(--vscode-terminal-hoverHighlightBackground)',
					'terminalCursor-background': 'var(--vscode-terminalCursor-background)',
					'terminalCursor-foreground': 'var(--vscode-terminalCursor-foreground)',
					'terminal-dropBackground': 'var(--vscode-terminal-dropBackground)',
					'terminal-tab-activeBorder': 'var(--vscode-terminal-tab-activeBorder)',
					'terminalCommandDecoration-defaultBackground': 'var(--vscode-terminalCommandDecoration-defaultBackground)',
					'terminalCommandDecoration-successBackground': 'var(--vscode-terminalCommandDecoration-successBackground)',
					'terminalCommandDecoration-errorBackground': 'var(--vscode-terminalCommandDecoration-errorBackground)',
					'terminalOverviewRuler-cursorForeground': 'var(--vscode-terminalOverviewRuler-cursorForeground)',
					'terminalOverviewRuler-findMatchForeground': 'var(--vscode-terminalOverviewRuler-findMatchForeground)',

					// debug colors
					'debugToolBar-background': 'var(--vscode-debugToolBar-background)',
					'debugToolBar-border': 'var(--vscode-debugToolBar-border)',
					'editor-stackFrameHighlightBackground': 'var(--vscode-editor-stackFrameHighlightBackground)',
					'editor-focusedStackFrameHighlightBackground': 'var(--vscode-editor-focusedStackFrameHighlightBackground)',
					'editor-inlineValuesForeground': 'var(--vscode-editor-inlineValuesForeground)',
					'editor-inlineValuesBackground': 'var(--vscode-editor-inlineValuesBackground)',
					'debugView-exceptionLabelForeground': 'var(--vscode-debugView-exceptionLabelForeground)',
					'debugView-exceptionLabelBackground': 'var(--vscode-debugView-exceptionLabelBackground)',
					'debugView-stateLabelForeground': 'var(--vscode-debugView-stateLabelForeground)',
					'debugView-stateLabelBackground': 'var(--vscode-debugView-stateLabelBackground)',
					'debugView-valueChangedHighlight': 'var(--vscode-debugView-valueChangedHighlight)',
					'debugTokenExpression-name': 'var(--vscode-debugTokenExpression-name)',
					'debugTokenExpression-value': 'var(--vscode-debugTokenExpression-value)',
					'debugTokenExpression-string': 'var(--vscode-debugTokenExpression-string)',
					'debugTokenExpression-boolean': 'var(--vscode-debugTokenExpression-boolean)',
					'debugTokenExpression-number': 'var(--vscode-debugTokenExpression-number)',
					'debugTokenExpression-error': 'var(--vscode-debugTokenExpression-error)',

					// welcome page colors
					'welcomePage-background': 'var(--vscode-welcomePage-background)',
					'welcomePage-progress-background': 'var(--vscode-welcomePage-progress-background)',
					'welcomePage-progress-foreground': 'var(--vscode-welcomePage-progress-foreground)',
					'welcomePage-tileBackground': 'var(--vscode-welcomePage-tileBackground)',
					'welcomePage-tileHoverBackground': 'var(--vscode-welcomePage-tileHoverBackground)',
					'welcomePage-tileBorder': 'var(--vscode-welcomePage-tileBorder)',
					'walkThrough-embeddedEditorBackground': 'var(--vscode-walkThrough-embeddedEditorBackground)',

					// git colors
					'gitDecoration-addedResourceForeground': 'var(--vscode-gitDecoration-addedResourceForeground)',
					'gitDecoration-modifiedResourceForeground': 'var(--vscode-gitDecoration-modifiedResourceForeground)',
					'gitDecoration-deletedResourceForeground': 'var(--vscode-gitDecoration-deletedResourceForeground)',
					'gitDecoration-renamedResourceForeground': 'var(--vscode-gitDecoration-renamedResourceForeground)',
					'gitDecoration-stageModifiedResourceForeground': 'var(--vscode-gitDecoration-stageModifiedResourceForeground)',
					'gitDecoration-stageDeletedResourceForeground': 'var(--vscode-gitDecoration-stageDeletedResourceForeground)',
					'gitDecoration-untrackedResourceForeground': 'var(--vscode-gitDecoration-untrackedResourceForeground)',
					'gitDecoration-ignoredResourceForeground': 'var(--vscode-gitDecoration-ignoredResourceForeground)',
					'gitDecoration-conflictingResourceForeground': 'var(--vscode-gitDecoration-conflictingResourceForeground)',
					'gitDecoration-submoduleResourceForeground': 'var(--vscode-gitDecoration-submoduleResourceForeground)',

					// settings editor colors
					'settings-headerForeground': 'var(--vscode-settings-headerForeground)',
					'settings-modifiedItemIndicator': 'var(--vscode-settings-modifiedItemIndicator)',
					'settings-dropdownBackground': 'var(--vscode-settings-dropdownBackground)',
					'settings-dropdownForeground': 'var(--vscode-settings-dropdownForeground)',
					'settings-dropdownBorder': 'var(--vscode-settings-dropdownBorder)',
					'settings-dropdownListBorder': 'var(--vscode-settings-dropdownListBorder)',
					'settings-checkboxBackground': 'var(--vscode-settings-checkboxBackground)',
					'settings-checkboxForeground': 'var(--vscode-settings-checkboxForeground)',
					'settings-checkboxBorder': 'var(--vscode-settings-checkboxBorder)',
					'settings-rowHoverBackground': 'var(--vscode-settings-rowHoverBackground)',
					'settings-textInputBackground': 'var(--vscode-settings-textInputBackground)',
					'settings-textInputForeground': 'var(--vscode-settings-textInputForeground)',
					'settings-textInputBorder': 'var(--vscode-settings-textInputBorder)',
					'settings-numberInputBackground': 'var(--vscode-settings-numberInputBackground)',
					'settings-numberInputForeground': 'var(--vscode-settings-numberInputForeground)',
					'settings-numberInputBorder': 'var(--vscode-settings-numberInputBorder)',
					'settings-focusedRowBackground': 'var(--vscode-settings-focusedRowBackground)',
					'settings-focusedRowBorder': 'var(--vscode-settings-focusedRowBorder)',
					'settings-sashBorder': 'var(--vscode-settings-sashBorder)',

					// breadcrumb colors
					'breadcrumb-foreground': 'var(--vscode-breadcrumb-foreground)',
					'breadcrumb-background': 'var(--vscode-breadcrumb-background)',
					'breadcrumb-focusForeground': 'var(--vscode-breadcrumb-focusForeground)',
					'breadcrumb-activeSelectionForeground': 'var(--vscode-breadcrumb-activeSelectionForeground)',
					'breadcrumbPicker-background': 'var(--vscode-breadcrumbPicker-background)',

					// snippet colors
					'editor-snippetTabstopHighlightBackground': 'var(--vscode-editor-snippetTabstopHighlightBackground)',
					'editor-snippetTabstopHighlightBorder': 'var(--vscode-editor-snippetTabstopHighlightBorder)',
					'editor-snippetFinalTabstopHighlightBackground': 'var(--vscode-editor-snippetFinalTabstopHighlightBackground)',
					'editor-snippetFinalTabstopHighlightBorder': 'var(--vscode-editor-snippetFinalTabstopHighlightBorder)',

					// symbol icon colors
					'symbolIcon-arrayForeground': 'var(--vscode-symbolIcon-arrayForeground)',
					'symbolIcon-booleanForeground': 'var(--vscode-symbolIcon-booleanForeground)',
					'symbolIcon-classForeground': 'var(--vscode-symbolIcon-classForeground)',
					'symbolIcon-colorForeground': 'var(--vscode-symbolIcon-colorForeground)',
					'symbolIcon-constantForeground': 'var(--vscode-symbolIcon-constantForeground)',
					'symbolIcon-constructorForeground': 'var(--vscode-symbolIcon-constructorForeground)',
					'symbolIcon-enumeratorForeground': 'var(--vscode-symbolIcon-enumeratorForeground)',
					'symbolIcon-enumeratorMemberForeground': 'var(--vscode-symbolIcon-enumeratorMemberForeground)',
					'symbolIcon-eventForeground': 'var(--vscode-symbolIcon-eventForeground)',
					'symbolIcon-fieldForeground': 'var(--vscode-symbolIcon-fieldForeground)',
					'symbolIcon-fileForeground': 'var(--vscode-symbolIcon-fileForeground)',
					'symbolIcon-folderForeground': 'var(--vscode-symbolIcon-folderForeground)',
					'symbolIcon-functionForeground': 'var(--vscode-symbolIcon-functionForeground)',
					'symbolIcon-interfaceForeground': 'var(--vscode-symbolIcon-interfaceForeground)',
					'symbolIcon-keyForeground': 'var(--vscode-symbolIcon-keyForeground)',
					'symbolIcon-keywordForeground': 'var(--vscode-symbolIcon-keywordForeground)',
					'symbolIcon-methodForeground': 'var(--vscode-symbolIcon-methodForeground)',
					'symbolIcon-moduleForeground': 'var(--vscode-symbolIcon-moduleForeground)',
					'symbolIcon-namespaceForeground': 'var(--vscode-symbolIcon-namespaceForeground)',
					'symbolIcon-nullForeground': 'var(--vscode-symbolIcon-nullForeground)',
					'symbolIcon-numberForeground': 'var(--vscode-symbolIcon-numberForeground)',
					'symbolIcon-objectForeground': 'var(--vscode-symbolIcon-objectForeground)',
					'symbolIcon-operatorForeground': 'var(--vscode-symbolIcon-operatorForeground)',
					'symbolIcon-packageForeground': 'var(--vscode-symbolIcon-packageForeground)',
					'symbolIcon-propertyForeground': 'var(--vscode-symbolIcon-propertyForeground)',
					'symbolIcon-referenceForeground': 'var(--vscode-symbolIcon-referenceForeground)',
					'symbolIcon-snippetForeground': 'var(--vscode-symbolIcon-snippetForeground)',
					'symbolIcon-stringForeground': 'var(--vscode-symbolIcon-stringForeground)',
					'symbolIcon-structForeground': 'var(--vscode-symbolIcon-structForeground)',
					'symbolIcon-textForeground': 'var(--vscode-symbolIcon-textForeground)',
					'symbolIcon-typeParameterForeground': 'var(--vscode-symbolIcon-typeParameterForeground)',
					'symbolIcon-unitForeground': 'var(--vscode-symbolIcon-unitForeground)',
					'symbolIcon-variableForeground': 'var(--vscode-symbolIcon-variableForeground)',

					// debug icon colors
					'debugIcon-breakpointForeground': 'var(--vscode-debugIcon-breakpointForeground)',
					'debugIcon-breakpointDisabledForeground': 'var(--vscode-debugIcon-breakpointDisabledForeground)',
					'debugIcon-breakpointUnverifiedForeground': 'var(--vscode-debugIcon-breakpointUnverifiedForeground)',
					'debugIcon-breakpointCurrentStackframeForeground': 'var(--vscode-debugIcon-breakpointCurrentStackframeForeground)',
					'debugIcon-breakpointStackframeForeground': 'var(--vscode-debugIcon-breakpointStackframeForeground)',
					'debugIcon-startForeground': 'var(--vscode-debugIcon-startForeground)',
					'debugIcon-pauseForeground': 'var(--vscode-debugIcon-pauseForeground)',
					'debugIcon-stopForeground': 'var(--vscode-debugIcon-stopForeground)',
					'debugIcon-disconnectForeground': 'var(--vscode-debugIcon-disconnectForeground)',
					'debugIcon-restartForeground': 'var(--vscode-debugIcon-restartForeground)',
					'debugIcon-stepOverForeground': 'var(--vscode-debugIcon-stepOverForeground)',
					'debugIcon-stepIntoForeground': 'var(--vscode-debugIcon-stepIntoForeground)',
					'debugIcon-stepOutForeground': 'var(--vscode-debugIcon-stepOutForeground)',
					'debugIcon-continueForeground': 'var(--vscode-debugIcon-continueForeground)',
					'debugIcon-stepBackForeground': 'var(--vscode-debugIcon-stepBackForeground)',
					'debugConsole-infoForeground': 'var(--vscode-debugConsole-infoForeground)',
					'debugConsole-warningForeground': 'var(--vscode-debugConsole-warningForeground)',
					'debugConsole-errorForeground': 'var(--vscode-debugConsole-errorForeground)',
					'debugConsole-sourceForeground': 'var(--vscode-debugConsole-sourceForeground)',
					'debugConsoleInputIcon-foreground': 'var(--vscode-debugConsoleInputIcon-foreground)',

					// notebook colors
					'notebook-cellBorderColor': 'var(--vscode-notebook-cellBorderColor)',
					'notebook-cellHoverBackground': 'var(--vscode-notebook-cellHoverBackground)',
					'notebook-cellInsertionIndicator': 'var(--vscode-notebook-cellInsertionIndicator)',
					'notebook-cellStatusBarItemHoverBackground': 'var(--vscode-notebook-cellStatusBarItemHoverBackground)',
					'notebook-cellToolbarSeparator': 'var(--vscode-notebook-cellToolbarSeparator)',
					'notebook-cellEditorBackground': 'var(--vscode-notebook-cellEditorBackground)',
					'notebook-focusedCellBackground': 'var(--vscode-notebook-focusedCellBackground)',
					'notebook-focusedCellBorder': 'var(--vscode-notebook-focusedCellBorder)',
					'notebook-focusedEditorBorder': 'var(--vscode-notebook-focusedEditorBorder)',
					'notebook-inactiveFocusedCellBorder': 'var(--vscode-notebook-inactiveFocusedCellBorder)',
					'notebook-inactiveSelectedCellBorder': 'var(--vscode-notebook-inactiveSelectedCellBorder)',
					'notebook-outputContainerBackgroundColor': 'var(--vscode-notebook-outputContainerBackgroundColor)',
					'notebook-outputContainerBorderColor': 'var(--vscode-notebook-outputContainerBorderColor)',
					'notebook-selectedCellBackground': 'var(--vscode-notebook-selectedCellBackground)',
					'notebook-selectedCellBorder': 'var(--vscode-notebook-selectedCellBorder)',
					'notebook-symbolHighlightBackground': 'var(--vscode-notebook-symbolHighlightBackground)',
					'notebookScrollbarSlider-activeBackground': 'var(--vscode-notebookScrollbarSlider-activeBackground)',
					'notebookScrollbarSlider-background': 'var(--vscode-notebookScrollbarSlider-background)',
					'notebookScrollbarSlider-hoverBackground': 'var(--vscode-notebookScrollbarSlider-hoverBackground)',
					'notebookStatusErrorIcon-foreground': 'var(--vscode-notebookStatusErrorIcon-foreground)',
					'notebookStatusRunningIcon-foreground': 'var(--vscode-notebookStatusRunningIcon-foreground)',
					'notebookStatusSuccessIcon-foreground': 'var(--vscode-notebookStatusSuccessIcon-foreground)',
					'notebookEditorOverviewRuler-runningCellForeground': 'var(--vscode-notebookEditorOverviewRuler-runningCellForeground)',

					// chart colors
					'charts-foreground': 'var(--vscode-charts-foreground)',
					'charts-lines': 'var(--vscode-charts-lines)',
					'charts-red': 'var(--vscode-charts-red)',
					'charts-blue': 'var(--vscode-charts-blue)',
					'charts-yellow': 'var(--vscode-charts-yellow)',
					'charts-orange': 'var(--vscode-charts-orange)',
					'charts-green': 'var(--vscode-charts-green)',
					'charts-purple': 'var(--vscode-charts-purple)',

					// ports colors
					'ports-iconRunningProcessForeground': 'var(--vscode-ports-iconRunningProcessForeground)',

					// tab colors
					'tab-activeBackground': 'var(--vscode-tab-activeBackground)',
					'tab-unfocusedActiveBackground': 'var(--vscode-tab-unfocusedActiveBackground)',
					'tab-activeForeground': 'var(--vscode-tab-activeForeground)',
					'tab-border': 'var(--vscode-tab-border)',
					'tab-activeBorder': 'var(--vscode-tab-activeBorder)',
					'tab-unfocusedActiveBorder': 'var(--vscode-tab-unfocusedActiveBorder)',
					'tab-activeBorderTop': 'var(--vscode-tab-activeBorderTop)',
					'tab-unfocusedActiveBorderTop': 'var(--vscode-tab-unfocusedActiveBorderTop)',
					'tab-lastPinnedBorder': 'var(--vscode-tab-lastPinnedBorder)',
					'tab-inactiveBackground': 'var(--vscode-tab-inactiveBackground)',
					'tab-unfocusedInactiveBackground': 'var(--vscode-tab-unfocusedInactiveBackground)',
					'tab-inactiveForeground': 'var(--vscode-tab-inactiveForeground)',
					'tab-unfocusedActiveForeground': 'var(--vscode-tab-unfocusedActiveForeground)',
					'tab-unfocusedInactiveForeground': 'var(--vscode-tab-unfocusedInactiveForeground)',
					'tab-hoverBackground': 'var(--vscode-tab-hoverBackground)',
					'tab-unfocusedHoverBackground': 'var(--vscode-tab-unfocusedHoverBackground)',
					'tab-hoverForeground': 'var(--vscode-tab-hoverForeground)',
					'tab-unfocusedHoverForeground': 'var(--vscode-tab-unfocusedHoverForeground)',
					'tab-hoverBorder': 'var(--vscode-tab-hoverBorder)',
					'tab-unfocusedHoverBorder': 'var(--vscode-tab-unfocusedHoverBorder)',
					'tab-activeModifiedBorder': 'var(--vscode-tab-activeModifiedBorder)',
					'tab-inactiveModifiedBorder': 'var(--vscode-tab-inactiveModifiedBorder)',
					'tab-unfocusedActiveModifiedBorder': 'var(--vscode-tab-unfocusedActiveModifiedBorder)',
					'tab-unfocusedInactiveModifiedBorder': 'var(--vscode-tab-unfocusedInactiveModifiedBorder)',

					// editor group colors
					'editorGroup-border': 'var(--vscode-editorGroup-border)',
					'editorGroup-dropBackground': 'var(--vscode-editorGroup-dropBackground)',
					'editorGroupHeader-noTabsBackground': 'var(--vscode-editorGroupHeader-noTabsBackground)',
					'editorGroupHeader-tabsBackground': 'var(--vscode-editorGroupHeader-tabsBackground)',
					'editorGroupHeader-tabsBorder': 'var(--vscode-editorGroupHeader-tabsBorder)',
					'editorGroupHeader-border': 'var(--vscode-editorGroupHeader-border)',
					'editorGroup-emptyBackground': 'var(--vscode-editorGroup-emptyBackground)',
					'editorGroup-focusedEmptyBorder': 'var(--vscode-editorGroup-focusedEmptyBorder)',
					'editorGroup-dropIntoPromptForeground': 'var(--vscode-editorGroup-dropIntoPromptForeground)',
					'editorGroup-dropIntoPromptBackground': 'var(--vscode-editorGroup-dropIntoPromptBackground)',
					'editorGroup-dropIntoPromptBorder': 'var(--vscode-editorGroup-dropIntoPromptBorder)',

					// editor pane colors
					'sideBySideEditor-horizontalBorder': 'var(--vscode-sideBySideEditor-horizontalBorder)',
					'sideBySideEditor-verticalBorder': 'var(--vscode-sideBySideEditor-verticalBorder)',

					// diff editor colors
					'diffEditor-insertedTextBackground': 'var(--vscode-diffEditor-insertedTextBackground)',
					'diffEditor-insertedTextBorder': 'var(--vscode-diffEditor-insertedTextBorder)',
					'diffEditor-removedTextBackground': 'var(--vscode-diffEditor-removedTextBackground)',
					'diffEditor-removedTextBorder': 'var(--vscode-diffEditor-removedTextBorder)',
					'diffEditor-insertedLineBackground': 'var(--vscode-diffEditor-insertedLineBackground)',
					'diffEditor-removedLineBackground': 'var(--vscode-diffEditor-removedLineBackground)',
					'diffEditorGutter-insertedLineBackground': 'var(--vscode-diffEditorGutter-insertedLineBackground)',
					'diffEditorGutter-removedLineBackground': 'var(--vscode-diffEditorGutter-removedLineBackground)',
					'diffEditorOverview-insertedForeground': 'var(--vscode-diffEditorOverview-insertedForeground)',
					'diffEditorOverview-removedForeground': 'var(--vscode-diffEditorOverview-removedForeground)',
					'diffEditor-unchangedRegionBackground': 'var(--vscode-diffEditor-unchangedRegionBackground)',
					'diffEditor-unchangedRegionForeground': 'var(--vscode-diffEditor-unchangedRegionForeground)',
					'diffEditor-unchangedCodeBackground': 'var(--vscode-diffEditor-unchangedCodeBackground)',

					// chat colors
					'chat-background': 'var(--vscode-chat-background)',
					'chat-border': 'var(--vscode-chat-border)',
					'chat-slashCommandBackground': 'var(--vscode-chat-slashCommandBackground)',
					'chat-slashCommandForeground': 'var(--vscode-chat-slashCommandForeground)',
					'chat-avatarBackground': 'var(--vscode-chat-avatarBackground)',
					'chat-avatarForeground': 'var(--vscode-chat-avatarForeground)',
					'chat-requestBackground': 'var(--vscode-chat-requestBackground)',
					'chat-requestBorder': 'var(--vscode-chat-requestBorder)',
				},
			},
		},
	},
	plugins: [
		require('@tailwindcss/typography')
	],
	prefix: 'pinnacleai-'
}
